[tools]
bun = "latest"
node = "latest"
usage = "latest"
neovim = "0.12.0"
deno = "latest"
java = "latest"
redis = "latest"
python = "3.13"

[settings]
idiomatic_version_file_enable_tools = ["bun"]

[settings.ruby]
compile = false
